version: '3.7'

services:
  postgres:
    image: quay.io/debezium/example-postgres:2.7
    container_name: postgres
    ports:
      - 5433:5432
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "max_replication_slots=4"
      -  "-c"
      - "wal_level=logical"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=5554"
#    networks:
#      - ${GLOBAL_NETWORK:-postgres}
networks:
  postgres:
    external: true