name: Order Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "order-service/**"
      - "common/**"
      - "infrastructure/**"
      - ".github/workflows/order-service-ci-cd.yml"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build order-service with dependencies
        run: mvn -pl order-service -am clean install -DskipTests

      - name: Build & Push Order Service Image
        run: mvn -f order-service/order-container/pom.xml com.google.cloud.tools:jib-maven-plugin:3.4.1:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}