name: Order Service CI/CD (Jib)

on:
  push:
    branches: [ "main" ]
    paths:
      - "order-service/**"
      - "common-*/**"
      - ".github/workflows/order-service-ci-cd.yml"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      - name: Install parent pom only
        run: mvn -f pom.xml install -N


      - name: Build common modules
        run: mvn -f common/pom.xml clean install -DskipTests


      - name: Build order-service
        run: mvn -f order-service/pom.xml clean install -DskipTests
      - name: Build & Push Order Service Image
        run: mvn -f order-service/order-container/pom.xml com.google.cloud.tools:jib-maven-plugin:3.4.1:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

